package com.example.drivingschool.models

data class Student(
    val id:Int?,
    val referee_id:Int?,
    val admission_number:String?,
    val first_name:String?,
    val middle_name:String?,
    val last_name:String?,
    val gender:String?,
    val email:String?,
    val registration_date:String?,
    val branch_id:Int?,
    val phone:String?,
    val driving_class_id:Int?,
    val id_number:String?,
    val course_type_id:Int?,
    val pdl:String?,
    val photo:String?,
    val discount:String?,
    val discount_approved:Int?,
    val status:Int?,
    val created_at:String?,
    val updated_at:String?,
)